on:
  push:
jobs:
  a:
    strategy:
      matrix:
        a: ${{fromJson('[]')}}
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  b:
    needs:
      - a
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
