on:
  push:
jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      colors: ${{ steps.colors.outputs.colors }}
    steps:
      - name: Define Colors
        id: colors
        run: |
          echo 'colors=[]' >> "$GITHUB_OUTPUT"
  a:
    if: needs.define-matrix.outputs.colors != '[]'
    needs:
      - define-matrix
    strategy:
      matrix:
        color: ${{ fromJSON(needs.define-matrix.outputs.colors) }}
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  b:
    needs:
      - a
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
